kind: Pod
apiVersion: v1
metadata:
  name: myapp
  labels:
    app.kubernetes.io/name: myapp
spec:
  containers:
  - name: myapp
    image: nginx
    resources:
      requests:
        memory: "128Mi"
        cpu: "500m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    volumes:
      - name:  mystorage
        mountPath:  /etc/certs
  volumes:
    - name:  mystorage
      emptyDir: {}
